services:
  asterisk:
    # image locally built if compose_build.yml is used 
    image: davidecavestro/iliad-asterisk-voip:latest
    network_mode: host
    volumes:
    - ./config:/etc/asterisk
    - ./spool:/var/spool/asterisk
    - ./log:/var/log/asterisk
    # - ./sounds/allarme.wav:/var/lib/asterisk/sounds/it/allarme.wav # in case you want to mount some sounds
    restart: unless-stopped
    healthcheck:
      test: /usr/sbin/asterisk -rx "core show sysinfo"
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
